# Generated by Django 4.1.3 on 2022-11-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRDCost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRDName',
            new_name='name',
        ),
    ]
