# Generated by Django 4.1.3 on 2022-11-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_prdcost_product_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='price'),
            preserve_default=False,
        ),
    ]
